### ISSUE TITLE
add_autoretry_behaviour() got multiple values for argument 'task'

### ISSUE THREAD

**Issue by vmathurpaytm** [open-craft/openedx-completion-aggregator#84]
I am running koa.master edx platform

I have installed the openedx-completion-aggregator  
and after running this command from edx platform **"./manage.py lms --settings production run_aggregator_service"**

I am getting this error "TypeError: add_autoretry_behaviour() got multiple values for argument 'task' "

```
   def update_aggregators(username, course_key, block_keys=(), force=False):
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/celery/app/__init__.py", line 66, in __inner
    app._task_from_fun(fun, **options)
  File "/edx/app/edxapp/venvs/edxapp/lib/python3.8/site-packages/celery/app/base.py", line 465, in _task_from_fun
    add_autoretry_behaviour(task, **options)
TypeError: add_autoretry_behaviour() got multiple values for argument 'task'

```

**Comment by arbrandes** [comment]
@vmathurpaytm, thanks for reporting this issue.  I'm not sure this block is supported in Koa, though.

@xitij2000, as the owner of one of the more recent significant commits, any idea?  Thanks!

**Comment by xitij2000** [comment]
Yes, this is currently not tested on Koa and it seems it is incompatible. We would love to get it working on Koa. Currently, we can't say when this will be upgraded to work on Koa, but we get a PR for it  we would definitely appreciate it.

**Comment by kshitiz305** [comment]
HI @xitij2000 this seems to be a very old issue I wish to know if this issue still requires contribution, if yes kindly let me know what are the todos else if there is something else that needs attention I am more than happy to contribute.

**Comment by xitij2000** [comment]
@kshitiz305 I think this plugin has been upgraded to support up to Maple now, and is likely to be upgraded to Palm as well. I doubt this issue is still present. 

I'm not sure what other todos you are looking for? I think most of the issues on this repo are quite stale.

**Comment by Agrendalath** [comment]
@xitij2000, yep, we're using this plugin with Nutmeg and will upgrade it to Palm. Closing.
