### ISSUE TITLE
 openedx-completion-aggregator in Tutor

### ISSUE THREAD

**Issue by yanivgn** [open-craft/openedx-completion-aggregator#91]
Hi, 
I want to run this plugin in Tutor inside k8s. Can someone help me to do it?
Thanks

**Comment by gabor-boros** [comment]
Hello @yanivgn,

What obstacles are you facing with?

**Comment by Agrendalath** [comment]
@gabor-boros, can we use cron jobs in Grove? If not, this will be yet another blocker for https://tasks.opencraft.com/browse/BB-7412.

**Comment by gabor-boros** [comment]
Yes, we can: https://gitlab.com/opencraft/dev/tutor-contrib-grove/-/blob/main/tutorgrove/plugin.py#L184

**Comment by Agrendalath** [comment]
@gabor-boros, awesome, thanks!

We can close it, then.
